spring.datasource.url=jdbc:mysql://localhost:3306/carecenter?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=770047
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework=DEBUG
rsa.public-key-location=public.pem
rsa.private-key-location=keypair.pem